development:
  cloud_name: hh7bbyfn0
  api_key: '653338967259463'
  api_secret: ID5kIfvBsmIlp2IRsD-Trr-jMws
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hh7bbyfn0
  api_key: '653338967259463'
  api_secret: ID5kIfvBsmIlp2IRsD-Trr-jMws
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hh7bbyfn0
  api_key: '653338967259463'
  api_secret: ID5kIfvBsmIlp2IRsD-Trr-jMws
  enhance_image_tag: true
  static_image_support: false
