development:
  cloud_name: hkl6wrjb3
  api_key: '759194423853157'
  api_secret: ErOYhBPRBXyDLCmFCVwcIYS6Y_M
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hkl6wrjb3
  api_key: '759194423853157'
  api_secret: ErOYhBPRBXyDLCmFCVwcIYS6Y_M
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hkl6wrjb3
  api_key: '759194423853157'
  api_secret: ErOYhBPRBXyDLCmFCVwcIYS6Y_M
  enhance_image_tag: true
  static_image_support: false
